### ISSUE TITLE
update module scaffolder for 1.10

### ISSUE THREAD

**Issue by rtpHarry** [Hazzamanic/orchardizer#17]
It's targeting a previous version of .net (should be bumped to 4.5.2 now).

This version moves over to using `packages.config` instead of directly referencing things in the libs folder. I think that means you will need to make some changes to the project.

Finally there is now asset support include in the form of an `/Assets/` folder and an assets.json.

**Comment by Hazzamanic** [comment]
I've added support for 1.10 and pushed to the gallery. 

Added the assets folder with a style.less file inside. Added an assets.json file with commands to create css from the less file. Also added packages.config. I've only included mvc as the sole nuget package, although all the orchard core modules seem to have a few other packages but I don't see quite why they are required. I'll ask on gitter maybe if anyone can explain this :)
