### ISSUE TITLE
Enabling Multi tenant

### ISSUE THREAD

**Issue by mach37** [Hazzamanic/orchardizer#24]
Hi can you support the plugin for multi tenants when building the modules in vs 2015 / 17

**Comment by Hazzamanic** [comment]
Can you give some more details as to what you mean?

**Comment by mach37** [comment]
I want to manage the plugin data at the tenant level or in other words, let me customize the builder output based on the tenant, like a logo customization for e.g.

**Comment by Hazzamanic** [comment]
Tenants are code agnostic, so not a concern for this extension
