### ISSUE TITLE
Support for VS 2015

### ISSUE THREAD

**Issue by dcinzona** [Hazzamanic/orchardizer#6]
Now that Visual Studio 2015 RC is available, it would be great to include support for this extension.

**Comment by SzymonSel** [comment]
Any progress here?

**Comment by Hazzamanic** [comment]
Hey,

Sorry for the like, year delay. It should support VS2015 now, I'm just trying to finish off a few issues with some new features before I push it onto the VS gallery. If you want to try out what I have so far you can download the vsix here: https://onedrive.live.com/redir?resid=52E4782EE489C830!113810&authkey=!AKyQmPTFCr6-Trc&ithint=file%2cvsix 

Just double click it and it should install in VS2015. I think it is mostly working, but yeah, still working out a few kinks :)

**Comment by SzymonSel** [comment]
Thanks Man!

**Comment by Hazzamanic** [comment]
I've pushed the latest version onto the gallery, with support for VS2015, so you should be able to grab it from there

**Comment by dcinzona** [comment]
Nice!  Thanks
